### ISSUE TITLE
初始化 init({debug:true})有错误

### ISSUE THREAD

**Issue by fromwhite** [whxaxes/easy-router#1]
router()里面没错误。
不错的资料。
专门下载代码学习，结合您这个路由和nodejs原本的路由，改了一个更适合自己的，作为测试和开发时配置使用。

**Comment by whxaxes** [comment]
最新版本已经没有init方法了哦，具体使用请看readme或者单元测试哈

**Comment by fromwhite** [comment]
是的，我本地是哪个canvas-test代码 我在看你那个边缘检测时想调试发现init方法没了，没想到升级了。
路由有限制吗，比如只能路由表映射asset目录 阻止其他访问  比如http://localhost:6060/app.js 阻止掉

**Comment by whxaxes** [comment]
是的，忘记同步那边的代码了，因为这个组件是用来快速测试用的，所以没有加限制呢，之后可以加一下
